/* Generated by scripts/release.cjs. Edit release.json, not this file. */
globalThis.PTGolfRelease = {
  "version": "92",
  "shell": [
    "css/golf.css",
    "css/style.css",
    "data/seed.json",
    "icon-maskable.svg",
    "icon.svg",
    "index.html",
    "js/app.js",
    "js/deletion-flow.js",
    "js/dialogs.js",
    "js/drafts.js",
    "js/exercise-media.js",
    "js/golf-data.js",
    "js/golf.js",
    "js/navigation.js",
    "js/offline.js",
    "js/persistence.js",
    "js/search.js",
    "js/store.js",
    "js/update.js",
    "manifest.webmanifest",
    "release-assets.js"
  ],
  "exercises": {
    "pt_pullup": [
      "docs/images/08_pullup.svg",
      "docs/images/guides/pt_pullup-end.webp",
      "docs/images/guides/pt_pullup-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_seatedrow": [
      "docs/images/09_seatedrow.svg",
      "docs/images/guides/pt_seatedrow-end.webp",
      "docs/images/guides/pt_seatedrow-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_latpulldown": [
      "docs/images/10_latpulldown.svg",
      "docs/images/guides/pt_latpulldown-end.webp",
      "docs/images/guides/pt_latpulldown-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_armpulldown": [
      "docs/images/11_armpulldown.svg",
      "docs/images/guides/pt_armpulldown-end.webp",
      "docs/images/guides/pt_armpulldown-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_dbpullover": [
      "docs/images/32_dbpullover.svg",
      "docs/images/guides/pt_dbpullover-end.webp",
      "docs/images/guides/pt_dbpullover-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_machinerow": [
      "docs/images/34_machinerow.svg",
      "docs/images/guides/pt_machinerow-end.webp",
      "docs/images/guides/pt_machinerow-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_seal_row": [
      "docs/images/guides/pt_seal_row-end.webp",
      "docs/images/guides/pt_seal_row-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_backextension": [
      "docs/images/38_backextension.svg",
      "docs/images/guides/pt_backextension-end.webp",
      "docs/images/guides/pt_backextension-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_armcurl": [
      "docs/images/07_armcurl.svg",
      "docs/images/guides/pt_armcurl-end.webp",
      "docs/images/guides/pt_armcurl-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_benchpress": [
      "docs/images/27_benchpress.svg",
      "docs/images/guides/pt_benchpress-end.webp",
      "docs/images/guides/pt_benchpress-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_chestpress": [
      "docs/images/43_chestpress.svg",
      "docs/images/guides/pt_chestpress-end.webp",
      "docs/images/guides/pt_chestpress-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_pecdeck": [
      "docs/images/44_pecdeck.svg",
      "docs/images/guides/pt_pecdeck-end.webp",
      "docs/images/guides/pt_pecdeck-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_facepull": [
      "docs/images/39_facepull.svg",
      "docs/images/guides/pt_facepull-end.webp",
      "docs/images/guides/pt_facepull-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_lateralraise": [
      "docs/images/40_lateralraise.svg",
      "docs/images/guides/pt_lateralraise-end.webp",
      "docs/images/guides/pt_lateralraise-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_uprightrow": [
      "docs/images/guides/pt_uprightrow-end.webp",
      "docs/images/guides/pt_uprightrow-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_vsquat": [
      "docs/images/12_vsquat.svg",
      "docs/images/guides/pt_vsquat-end.webp",
      "docs/images/guides/pt_vsquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_squat": [
      "docs/images/13_squat.svg",
      "docs/images/guides/pt_squat-end.webp",
      "docs/images/guides/pt_squat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_halfsquat": [
      "docs/images/05_halfsquat.svg",
      "docs/images/guides/pt_halfsquat-end.webp",
      "docs/images/guides/pt_halfsquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_frontsquat": [
      "docs/images/06_frontsquat.svg",
      "docs/images/guides/pt_frontsquat-end.webp",
      "docs/images/guides/pt_frontsquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_heelsquat": [
      "docs/images/guides/pt_heelsquat-end.webp",
      "docs/images/guides/pt_heelsquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_gobletsquat": [
      "docs/images/41_gobletsquat.svg",
      "docs/images/guides/pt_gobletsquat-end.webp",
      "docs/images/guides/pt_gobletsquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_widesquat": [
      "docs/images/33_widesquat.svg",
      "docs/images/guides/pt_widesquat-end.webp",
      "docs/images/guides/pt_widesquat-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_dumbbell_rdl": [
      "docs/images/guides/pt_dumbbell_rdl-end.webp",
      "docs/images/guides/pt_dumbbell_rdl-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_legcurl": [
      "docs/images/14_legcurl.svg",
      "docs/images/guides/pt_legcurl-end.webp",
      "docs/images/guides/pt_legcurl-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_adduction": [
      "docs/images/15_adduction.svg",
      "docs/images/guides/pt_adduction-end.webp",
      "docs/images/guides/pt_adduction-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_legextension": [
      "docs/images/16_legextension.svg",
      "docs/images/guides/pt_legextension-end.webp",
      "docs/images/guides/pt_legextension-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_legpress": [
      "docs/images/36_legpress.svg",
      "docs/images/guides/pt_legpress-end.webp",
      "docs/images/guides/pt_legpress-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_wide_sidelunge_stretch": [
      "docs/images/guides/pt_wide_sidelunge_stretch-end.webp",
      "docs/images/guides/pt_wide_sidelunge_stretch-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_hip_openclose_stretch": [
      "docs/images/guides/pt_hip_openclose_stretch-end.webp",
      "docs/images/guides/pt_hip_openclose_stretch-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_daily_hamstring": [
      "docs/images/19_hamstring.svg",
      "docs/images/guides/pt_daily_hamstring-end.webp",
      "docs/images/guides/pt_daily_hamstring-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_daily_piriformis": [
      "docs/images/20_piriformis.svg",
      "docs/images/guides/pt_daily_piriformis-end.webp",
      "docs/images/guides/pt_daily_piriformis-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_plank": [
      "docs/images/18_plank.svg",
      "docs/images/guides/pt_plank-end.webp",
      "docs/images/guides/pt_plank-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_daily_foam": [
      "docs/images/21_foam.svg",
      "docs/images/guides/pt_daily_foam-end.webp",
      "docs/images/guides/pt_daily_foam-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_openbook": [
      "docs/images/26_openbook.svg",
      "docs/images/guides/pt_openbook-end.webp",
      "docs/images/guides/pt_openbook-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_rehab_quadset": [
      "docs/images/01_quadset.svg",
      "docs/images/guides/pt_rehab_quadset-end.webp",
      "docs/images/guides/pt_rehab_quadset-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_rehab_slr": [
      "docs/images/02_slr.svg",
      "docs/images/guides/pt_rehab_slr-end.webp",
      "docs/images/guides/pt_rehab_slr-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_rehab_clamshell": [
      "docs/images/03_clamshell.svg",
      "docs/images/guides/pt_rehab_clamshell-end.webp",
      "docs/images/guides/pt_rehab_clamshell-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_rehab_sslr": [
      "docs/images/04_sslr.svg",
      "docs/images/guides/pt_rehab_sslr-end.webp",
      "docs/images/guides/pt_rehab_sslr-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_bridge": [
      "docs/images/25_bridge.svg",
      "docs/images/guides/pt_bridge-end.webp",
      "docs/images/guides/pt_bridge-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_birddog": [
      "docs/images/22_birddog.svg",
      "docs/images/guides/pt_birddog-end.webp",
      "docs/images/guides/pt_birddog-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_deadbug": [
      "docs/images/17_deadbug.svg",
      "docs/images/guides/pt_deadbug-end.webp",
      "docs/images/guides/pt_deadbug-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_tbalance": [
      "docs/images/23_tbalance.svg",
      "docs/images/guides/pt_tbalance-end.webp",
      "docs/images/guides/pt_tbalance-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_stepup": [
      "docs/images/24_stepup.svg",
      "docs/images/guides/pt_stepup-end.webp",
      "docs/images/guides/pt_stepup-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_tailbone_raise": [
      "docs/images/30_tailbone_raise.svg",
      "docs/images/guides/pt_tailbone_raise-end.webp",
      "docs/images/guides/pt_tailbone_raise-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_rotationlunge": [
      "docs/images/31_rotationlunge.svg",
      "docs/images/guides/pt_rotationlunge-end.webp",
      "docs/images/guides/pt_rotationlunge-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_bosurotation": [
      "docs/images/35_bosurotation.svg",
      "docs/images/guides/pt_bosurotation-end.webp",
      "docs/images/guides/pt_bosurotation-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_sldl": [
      "docs/images/42_sldl.svg",
      "docs/images/guides/pt_sldl-end.webp",
      "docs/images/guides/pt_sldl-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_pushdown": [
      "docs/images/37_pushdown.svg",
      "samples/pushdown-3d/combined-end.png",
      "samples/pushdown-3d/combined-start.png",
      "samples/pushdown-3d/pushdown.js",
      "samples/pushdown-3d/three.min.js",
      "samples/pushdown-3d/viewer.html"
    ],
    "pt_dumbbell_press": [
      "docs/images/guides/pt_dumbbell_press-end.webp",
      "docs/images/guides/pt_dumbbell_press-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ],
    "pt_incline_smith_press": [
      "docs/images/guides/pt_incline_smith_press-end.webp",
      "docs/images/guides/pt_incline_smith_press-start.webp",
      "js/exercise-media.js",
      "media/3d/poses.js",
      "media/3d/viewer.html",
      "media/3d/viewer.js",
      "samples/pushdown-3d/three.min.js"
    ]
  }
};
