const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseRequest}=require('../scripts/deletion-requests.cjs');
const source=fs.readFileSync(path.resolve(__dirname,'../js/deletion-flow.js'),'utf8');
const opened=[];
const ctx={window:{open:(url,target,features)=>{opened.push({url,target,features});return {}; }},URLSearchParams,Date};
vm.createContext(ctx);vm.runInContext(source,ctx);
const flow=ctx.window.DeletionFlow;
const request={kind:'exercise',contentId:'pt_pushup',title:'푸시업',requestedAt:'2026-09-27T00:00:00.000Z',memo:'외부로 보내면 안 되는 개인 메모'};
const issue=new URL(flow.issueUrl(request));
assert.equal(issue.origin,'https://github.com');assert.equal(issue.pathname,'/peoplenhpark/PT-GOLF/issues/new');
assert.equal(issue.searchParams.get('template'),'content-removal.md');assert.equal(issue.searchParams.get('labels'),'deletion-request');
assert.match(issue.searchParams.get('title'),/푸시업 \(pt_pushup\)/);
assert.match(issue.searchParams.get('body'),/<!-- pt-golf-deletion-request:v1 -->\ncontent-kind: exercise\ncontent-id: pt_pushup\n<!-- \/pt-golf-deletion-request -->/);
assert.equal(parseRequest({number:7,state:'open',body:issue.searchParams.get('body')}).id,'pt_pushup','the generated request must pass the deployment parser');
assert(!issue.searchParams.get('body').includes(request.memo),'personal memo must not leave the device');
assert.throws(()=>flow.issueUrl({...request,kind:'unknown'}),/삭제 요청 정보를/);
assert.throws(()=>flow.issueUrl({...request,contentId:'bad id'}),/삭제 요청 정보를/);
assert.equal(flow.openIssue(request).attempted,true);assert.equal(opened.length,1);assert.equal(opened[0].target,'_blank');assert.match(opened[0].features,/noopener/);
ctx.window.open=()=>null;assert.equal(flow.openIssue(request).attempted,true,'noopener and popup blocking both return null, so only the attempt is knowable');
ctx.window.open=()=>{throw Error('navigation unavailable');};assert.equal(flow.openIssue(request).attempted,false);
console.log('PASS: deletion hand-off URL is structured, template-labelled, validated, and excludes unrelated private fields.');
