/* Generate release references and an offline manifest. No bundler is needed. */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8').replace(/^\uFEFF/, '');
const release = JSON.parse(read('release.json'));
if (!/^\d+$/.test(String(release.version))) throw new Error('release.json version must be numeric');
const version = String(release.version);
const check = process.argv.includes('--check');
let changed = 0;
function output(file, value) {
  const before = fs.existsSync(path.join(root, file)) ? read(file) : '';
  if (before === value) return;
  changed++;
  if (check) throw new Error(file + ' is out of date; run npm run release:prepare');
  fs.writeFileSync(path.join(root, file), value, 'utf8');
}
const runtimeFiles = ['index.html', ...fs.readdirSync(path.join(root, 'js')).filter(f=>f.endsWith('.js')).map(f=>'js/'+f),
  'media/3d/viewer.html', 'media/3d/viewer.js', 'samples/pushdown-3d/index.html', 'samples/pushdown-3d/viewer.html',
  ...fs.readdirSync(path.join(root, 'media/golf3d')).filter(f=>f.endsWith('.html')).map(f=>'media/golf3d/'+f)];
for (const file of process.argv.includes('--manifest-only') ? [] : runtimeFiles) {
  const code = read(file).replace(/([?&]v=)\d+/g, '$1' + version)
    .replace(/(ASSET_VER\s*=\s*)'\d+'/g, '$1' + "'" + version + "'");
  output(file, code);
}
const scope = 'https://offline.invalid/PT-GOLF/';
const clean = value => {
  const url = new URL(value, scope);
  if (!url.href.startsWith(scope)) throw new Error('External asset in offline manifest: ' + value);
  return url.pathname.slice(new URL(scope).pathname.length) || 'index.html';
};
function htmlAssets(file) {
  const code = read(file);
  return [...code.matchAll(/<(?:script|link)\b[^>]*?(?:src|href)=["']([^"']+)["'][^>]*>/g)]
    .filter(m=>!/^https?:/.test(m[1]))
    .map(m=>clean(new URL(m[1], new URL(file, scope)).href));
}
const ctx = { window: {} };
vm.runInNewContext(read('js/exercise-media.js'), ctx);
const seed = JSON.parse(read('data/seed.json'));
const exercises = {};
for (const [id, media] of Object.entries(ctx.window.ExerciseMedia)) {
  const viewer = clean(media.viewer);
  const legacyImage = seed.exercises.find(e=>e.id===id)?.image;
  exercises[id] = [...new Set([...(media.images || []).map(clean), ...(legacyImage ? [clean(legacyImage)] : []), viewer,
    ...htmlAssets(viewer)])].sort();
}
const shell = [...new Set(['index.html', 'data/seed.json', 'manifest.webmanifest', 'icon.svg', 'icon-maskable.svg',
  'release-assets.js', ...htmlAssets('index.html')])].sort();
const all = new Set([...shell, ...Object.values(exercises).flat()]);
for (const file of all) {
  if (file === 'release-assets.js') continue;
  if (!fs.existsSync(path.join(root, file))) throw new Error('Missing release asset: ' + file);
}
output('release-assets.js', '/* Generated by scripts/release.cjs. Edit release.json, not this file. */\n' +
  'globalThis.PTGolfRelease = ' + JSON.stringify({ version, shell, exercises }, null, 2) + ';\n');
console.log((check ? 'Verified' : 'Prepared') + ' v' + version + ': ' + shell.length + ' shell assets, ' + Object.keys(exercises).length + ' offline exercises; ' + changed + ' generated/reference files updated.');
